### ISSUE TITLE
epic: port the implementation and optimizations of leveldb v1.23

### ISSUE THREAD

**Issue by cfzjywxk** [TiDBHackers/ldb#1]
This is the first stage, in this stage, a high-performance leveldb implementation in rust would be implemented. This will be the basis for subsequent experiments and it's also a good opportunity to learn the details of leveldb as well as rust programming for the stand alone storage engines.

The [leveldb v1.23](https://github.com/google/leveldb/releases/tag/1.23) is the latest released leveldb version.
Try to port the implementations of it:
- [ ] The memtable, including the skiplist/skipmap implementation and related concurrent functional tests and performance tests.
- [ ] The key value encoding utilities, including the user and internal key encode and decode, and related functional tests.
- [ ] Implement `WriteBatch` related processing utilities and functional tests.
- [ ] The WAL log processing utilities, the log writer, the log reader, and functional tests.
- [ ] The version management system, including the `VersionSet`, `VersionEdit`, and the `Version` related functions and tests.
- [ ] The manifest system which is the WAL log of the version system, with functional tests.
- [ ] The block and table cache, the LRU cache implementations, and functional and performance tests.
- [ ] The minor compaction work, frozen and flush the level-0 memtable to disk.
- [ ] The major compaction work, score calculation, file generation, work scheduling, functional tests, and performance tests.
- [ ] Make it concurrent, implement the full `db_bench` logic, and use it to evaluate current performance.

**Comment by you06** [comment]
There is an off-the-shelf lock-free skiplist provided by [crossbeam](https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-skiplist), to use it or write a new one, which do we prefer?

**Comment by cfzjywxk** [comment]
@you06 
We could do some benchmark tests for both the skiplist implementation itself and later with the `db_bench`. This is an interesting and important module that we need to do more research and experiments on, for example we may also try to use a lock-free b-tree like structure too.
